### PR TITLE
IWF-438: Validate if RPC method is not final

### LINKED ISSUE #286: Validate RPC methods should not be final
**Context**
Otherwise byteBuddy won't work when intercepting the call.

All method in Java by default is not final, but for Kotlin, `open` must be added for the RPC method to make it not final.

See https://stackoverflow.com/questions/54043234/bytebuddy-method-interception-doesnt-work-in-kotlin 

**Goal**
We should throw error when the rpcStub is created  or workflow is registered (prefer former). Because when invoking later, there is not obivous errors for this issues.

### PR DESCRIPTION
**Pull request by lwolczynski**
### Checklist
- [ ] Code compiles correctly
- [ ] Tests for the changes have been added
- [ ] All tests passing
- [ ] **This PR change is backwards-compatible**
- [ ] **This PR CONTAINS a (planned) breaking change** (it is NOT backwards-compatible)

### Related Issue
Closes #286

### CODE REVIEW

**Review by samuel27m — APPROVED** [review]
LGTM! Is there a way to add Unit Testing for this? I'm guessing the answer is no, but always good to double-check.

**Comment by lwolczynski** [comment]
> LGTM! Is there a way to add Unit Testing for this? I'm guessing the answer is no, but always good to double-check.

I think there can be. Let me try!

**Comment by lwolczynski** [comment]
> > LGTM! Is there a way to add Unit Testing for this? I'm guessing the answer is no, but always good to double-check.
> 
> I think there can be. Let me try!

That would be more complicated than expected. Adding a workflow with a finalized RPC method causes the service to crash at the start, which makes everything fail. See this commit: c210761c2e3ca1944795244af784d88837ac859b

To implement the test, I would need to spin up two Spring Boot apps: one that implements a finalized RPC method and another without it. Then, the first one would be only created to verify that it fails at the start, and the other one would be used for all existing tests. This seems to be somewhat complicated and not worth investing the required effort

**Comment by samuel27m** [comment]
> > > LGTM! Is there a way to add Unit Testing for this? I'm guessing the answer is no, but always good to double-check.
> > 
> > 
> > I think there can be. Let me try!
> 
> That would be more complicated than expected. Adding a workflow with a finalized RPC method causes the service to crash at the start, which makes everything fail. See this commit: [c210761](https://github.com/indeedeng/iwf-java-sdk/commit/c210761c2e3ca1944795244af784d88837ac859b)
> 
> To implement the test, I would need to spin up two Spring Boot apps: one that implements a finalized RPC method and another without it. Then, the first one would be only created to verify that it fails at the start, and the other one would be used for all existing tests. This seems to be somewhat complicated and not worth investing the required effort

Makes sense! Thanks so much for looking into that

**Pull request merged**
