### PR TITLE
IWF-405: rename and validate failure recovery policy

### PR DESCRIPTION
**Pull request by longquanzheng**
### Checklist
- [x] Code compiles correctly
- [x] Tests for the changes have been added
- [x] All tests passing
- [x] **This PR change is backwards-compatible**
- [ ] **This PR CONTAINS a (planned) breaking change** (it is NOT backwards-compatible)

### Related Issue
Closes #<issue_number>

### CODE REVIEW

**Comment by lwolczynski** [comment]
Closes #277

**Comment by lwolczynski** [comment]
`setProceedAfterRetryExhaustedOnExecuteFailure`
`setProceedAfterRetryExhaustedOnWaitUntilFailure`

Do we need to stick to the `Failure` suffix? I think `RetryExhausted` is enough info. I suggest:

`setProceedOnExecuteAfterRetryPolicyExhausted`
`setProceedOnWaitUntilAfterRetryPolicyExhausted`

**Comment by longquanzheng** [comment]
> `setProceedAfterRetryExhaustedOnExecuteFailure` `setProceedAfterRetryExhaustedOnWaitUntilFailure`
> 
> Do we need to stick to the `Failure` suffix? I think `RetryExhausted` is enough info. I suggest:
> 
> `setProceedOnExecuteAfterRetryPolicyExhausted` `setProceedOnWaitUntilAfterRetryPolicyExhausted`

That's a great idea. Love it. Thanks!

**Comment by longquanzheng** [comment]
> setProceedOnExecuteAfterRetryPolicyExhausted
> setProceedOnWaitUntilAfterRetryPolicyExhausted

You meant:

> setProceedAfterRetryPolicyExhaustedOnExecute
> setProceedAfterRetryPolicyExhaustedOnWaitUntil

Right? 

I also like what @ktrops suggested to put "onExeute" and "onWaitUnti" at the end for easier to read, and also less confusing.

"ProceedOnExecute" could make it feel like "Proceed on to execute", but its actually proceed after execute.

**Comment by longquanzheng** [comment]
Yes I like that, using `When` make it very clear

**Comment by ktrops** [comment]
How about?
`setProceedWhenRetryPolicyExhaustedOnExecute`
`setProceedWhenRetryPolicyExhaustedOnWaitUntil`

**Comment by longquanzheng** [comment]
> How about? `setProceedWhenRetryPolicyExhaustedOnExecute` `setProceedWhenRetryPolicyExhaustedOnWaitUntil`

Lol. Yeah I like this the most so far 😂 
WDYT? @lwolczynski 
A fun journey for this renaming discussion :P

**Comment by ktrops** [comment]
Or

`setProceedToWhenRetryPolicyExhaustedOnExecute`
`setProceedToWhenRetryPolicyExhaustedOnWaitUntil`

**Comment by lwolczynski** [comment]
> > How about? `setProceedWhenRetryPolicyExhaustedOnExecute` `setProceedWhenRetryPolicyExhaustedOnWaitUntil`
> 
> Lol. Yeah I like this the most so far 😂 WDYT? @lwolczynski A fun journey for this renaming discussion :P

Fine either way

**Comment by ktrops** [comment]
> Fine either way. I personally would try to omit the On, but it's okay

I'm ok with omitting the `on`

**Pull request merged**
